In [2]:
# 首先 import 必要的模块
import pandas as pd 
import numpy as np

import lightgbm as lgbm
from lightgbm.sklearn import LGBMClassifier

from sklearn.model_selection import GridSearchCV

import matplotlib.pyplot as plt
%matplotlib inline

/Users/na/anaconda3/lib/python3.6/site-packages/lightgbm/__init__.py:46: UserWarning: Starting from version 2.2.1, the library file in distribution wheels for macOS is built by the Apple Clang (Xcode_9.4.1) compiler.
This means that in case of installing LightGBM from PyPI via the ``pip install lightgbm`` command, you don't need to install the gcc compiler anymore.
Instead of that, you need to install the OpenMP library, which is required for running LightGBM on the system with the Apple Clang compiler.
You can install the OpenMP library by the following command: ``brew install libomp``.
  "You can install the OpenMP library by the following command: ``brew install libomp``.", UserWarning)

In [3]:
# 读取数据
x_test = pd.read_csv("6-11ExtractData_FinalTest.csv")
x_test.head()

,source_system_tab,source_screen_name,source_type,song_length,language,city,bd,gender,registered_via,times_Mon,...,lyricist_hash_0,lyricist_hash_1,lyricist_hash_2,lyricist_hash_3,lyricist_hash_4,lyricist_hash_5,lyricist_hash_6,lyricist_hash_7,lyricist_hash_8,lyricist_hash_9
0,4,8,4,14,4,0,21,0,7,19,...,0.0,31172.0,-15586.0,46758.0,15586.0,-31172.0,-15586.0,-31172.0,15586.0,-15586.0
1,4,8,4,21,4,0,21,0,7,19,...,0.0,31172.0,-15586.0,49152.0,15586.0,-31172.0,-15586.0,-31172.0,15586.0,-15586.0
2,1,20,10,21,2,0,21,0,4,0,...,0.0,31172.0,-15586.0,47337.0,15586.0,-31172.0,-15586.0,-31172.0,15586.0,-15586.0
3,6,15,8,19,8,14,30,2,9,117,...,0.0,31172.0,-15586.0,46758.0,15586.0,-31172.0,-15586.0,-31172.0,15586.0,-15586.0
4,6,15,8,13,0,14,30,2,9,117,...,0.0,31172.0,-15586.0,46758.0,15586.0,-31172.0,-15586.0,-31172.0,15586.0,-15586.0

In [4]:
import pickle

lgbm_best = pickle.load(open('LightGBM_.pkl2','rb'))
y_test_pred = lgbm_best.predict_proba(x_test)

/Users/na/anaconda3/lib/python3.6/site-packages/sklearn/base.py:311: UserWarning: Trying to unpickle estimator LabelEncoder from version 0.20.2 when using version 0.19.1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)

In [5]:
y_test_pred.shape

(1000000, 2)

In [10]:
out_df = pd.DataFrame(y_test_pred)
test_id = pd.read_csv("6-ID.csv")
out_df = pd.concat([test_id,out_df],axis = 1)
out_df.head()

   id         0         1
0   0  0.370605  0.629395
1   1  0.352659  0.647341
2   2  0.949104  0.050896
3   3  0.872797  0.127203
4   4  0.827144  0.172856

In [9]:
out_df.to_csv('6-LightGBM_final2.csv',index = False)